
services:
  # ──────────── backend ────────────
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks: [habit-network]
    restart: always

  # ──────────── frontend (Nginx SPA) ────────────
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks: [habit-network]
    restart: always

  # ──────────── Postgres ────────────
  db:
    image: postgres:13
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: [habit-network]
    restart: always
    healthcheck:           
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  # ──────────── pytest ────────────
  tests:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL_TEST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    entrypoint: ["/app/tests/entrypoint.sh"]   
    networks: [habit-network]
    restart: "no"
    volumes:
      - ./coverage:/app/htmlcov

networks:
  habit-network:
    driver: bridge

volumes:
  postgres_data:
