
services:
  # ──────────── backend ────────────
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/habit_tracker
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - DAILY_REMINDER_TIME=${DAILY_REMINDER_TIME:-09:00}
    networks: [habit-network]
    restart: always

  # ──────────── frontend (Nginx SPA) ────────────
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks: [habit-network]
    restart: always

  # ──────────── Postgres ────────────
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=habit_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: [habit-network]
    restart: always
    healthcheck:           
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  # ──────────── pytest ────────────
  tests:
    build: ./backend        
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/habit_tracker_test
      - POSTGRES_PASSWORD=postgres
    entrypoint: ["/app/tests/entrypoint.sh"]   
    networks: [habit-network]
    restart: "no"
    volumes:
      - ./coverage:/app/htmlcov

  # ──────────── Telegram Scheduler ────────────
  telegram-scheduler:
    build: ./backend
    depends_on:
      - db
      - backend
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/habit_tracker
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - DAILY_REMINDER_TIME=${DAILY_REMINDER_TIME:-09:00}
    command: python scheduler.py
    networks: [habit-network]
    restart: always
    volumes:
      - telegram_logs:/var/log

networks:
  habit-network:
    driver: bridge

volumes:
  postgres_data:
  telegram_logs:
